---
# tasks insttall Declaritive Onboarding Latest

#Bypass for userAuth
 - ansible.builtin.stat:
     path: "{{ File_Location }}"/credentials.yml
   register: credentials_bypass

 - ansible.builtin.include_vars:
     file: "{{ File_Location }}"/credentials.yml
   when: credentials_bypass.stat.exists