---
# tasks insttall Declaritive Onboarding Latest

 - name: Get Checksum of Modified file
   ansible.builtin.stat:
     path : "{{ ASM_Policy_File }}"
   register: second_file

 - name: Master Template SHA1
   ansible.builtin.set_fact:
     file2_sha: "{{ second_file.stat.checksum }}"

 - name: Compilation Changed
   ansible.builtin.set_fact:
     sha_matched: = "{{file2_sha and file1_sha}}"
   when:  file2_sha != file1_sha
   
 - name: Check if Repo Exists
   ansible.builtin.uri:
     url: "{{git_api_url}}{{git_workspace}}"
     method: GET
     user: "{{git_username}}"
     password: "{{git_password}}"
     force_basic_auth: yes
     status_code: 200
     body_format: json
   delegate_to: localhost
   register: repo_info
   when: sha_matched is defined

 - name: check if repo exists
   ansible.builtin.set_fact:
     student_id: "{{ item }}"
   with_items: "{{repo_info.json['values']}}"
   when: sha_matched is defined and item.name == repo_name

 - name: Create a Bitbucket Repo
   ansible.builtin.uri:
     url: "{{git_api_url}}{{git_workspace}}/{{repo_name}}"
     method: POST
     user: "{{git_username}}"
     password: "{{git_password}}"
     body: "{{ lookup('template','create_repo.j2', split_lines=False) }}"
     force_basic_auth: yes
     status_code: 200
     body_format: json
   delegate_to: localhost
   when: sha_matched is defined and student_id is undefined

 - pause:
     seconds: 20
   when: sha_matched is defined and student_id is undefined

 - name: Create a directory if it does not exist
   ansible.builtin.file:
     path: "/root/asm-xml-files-student"
     state: directory
     mode: '0755'

 - name: Initialize Git
   ansible.builtin.shell: |
     cd /root/asm-xml-files-student/
     git init
     exit 0
   when: sha_matched is defined and student_id is undefined

 - name: Git checkout 3
   ansible.builtin.git:
     repo: "https://{{git_username | urlencode }}:{{git_password | urlencode}}@{{git_website[8:]}}{{git_workspace}}/{{repo_name}}"
     dest: /root/asm-xml-files-student
   ignore_errors: true
   when: sha_matched is defined

 - name: Copy Modified File to Git Repo
   ansible.builtin.copy:
     src: "{{ASM_Policy_File}}"
     dest: "/root/asm-xml-files-student/{{ASM_Final_File_Name}}"
   when: sha_matched is defined
   register: file_name_output

 - ansible.builtin.debug: 
     var: file_name_output

 - name: Initial Commit Changes to Git
   ansible.builtin.shell: |
     cd /root/asm-xml-files-student/
     git remote add origin "https://{{git_username | urlencode }}:{{git_password | urlencode}}@{{git_website[8:]}}{{git_workspace}}/{{repo_name}}.git"
     git add .
     git commit -m "ASM File Update $(date +"%Y-%m-%d %H:%M:%S")"
     git push -u origin master
     exit 0
   when: sha_matched is defined and student_id is undefined

 - name: Commit Changes to Git
   ansible.builtin.shell: |
     cd /root/asm-xml-files-student/
     git add .
     git commit -m "ASM File Update $(date +"%Y-%m-%d %H:%M:%S")"
     git push
     exit 0
   when: sha_matched is defined and student_id is defined