- name: Download latest AS3 RPM
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    as3_uri: "https://github.com/F5Networks/f5-appsvcs-extension/releases"
  
  tasks:

  - name: Get latest AS3 RPM version
    action: shell curl -s {{as3_uri}} | grep -E rpm | head -1 | cut -d "/" -f 7 | cut -d "=" -f 1 |  cut -d "\"" -f 1
    register: as3_output

  - debug:
     var: as3_output.stdout_lines[0]

  - set_fact:
     as3_release: "{{as3_output.stdout_lines[0]}}"

  - name: Get latest AS3 RPM version
    action: shell curl -s {{as3_uri}} | grep -E rpm | head -1 | cut -d "/" -f 6
    register: as3_output

  - debug:
     var: as3_output.stdout_lines[0]

  - set_fact:
     as3_release_tag: "{{as3_output.stdout_lines[0]}}"

  - name: Grab AS3 RPM from github
    get_url:
     url: "{{as3_uri}}/download/{{as3_release_tag}}/{{as3_release}}?raw=true"
     dest: "~/"
     validate_certs: false

- name: Install AS3 package to BIG-IP
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Set a fact named 'provider' with BIG-IP login information
      set_fact:
       provider:
        server: "12.202.13.183"
        user: "admin"
        password: "$1Ig#68#ImJi"
        server_port: 8443
        validate_certs: no

    - name: Grab the AS3 version from the home directory
      shell: ls -Art ~/*.rpm | tail -n 1 | rev | cut -d/ -f 1 | rev
      register: ls_output

    - set_fact:
       as3_rpm: "{{ls_output.stdout}}"

    - name: Install AS3
      bigip_iapplx_package:
       package: "~/{{as3_rpm}}"
       provider: "{{provider}}"
