---
# tasks insttall Declaritive Onboarding Latest

 - name: Get latest DO RPM name
   ansible.builtin.shell: curl -s {{do_uri}} | grep -E rpm | head -1 | cut -d "/" -f 7 | cut -d "=" -f 1 |  cut -d "\"" -f 1
   register: do_output

 - ansible.builtin.set_fact:
    do_release: "{{do_output.stdout_lines[0]}}"

 - name: Get latest DO RPM version
   ansible.builtin.shell: curl -s {{do_uri}} | grep -E rpm | head -1 | cut -d "/" -f 6
   register: do_output

 - ansible.builtin.set_fact:
    do_release_tag: "{{do_output.stdout_lines[0]}}"

 - name: Grab DO RPM from github
   ansible.builtin.get_url:
    url: "{{do_uri}}/download/{{do_release_tag}}/{{do_release}}?raw=true"
    dest: "~/"
    validate_certs: false

 - name: Grab the DO version from the home directory
   ansible.builtin.shell: ls -Art ~/*.rpm | tail -n 1 | rev | cut -d/ -f 1 | rev
   register: ls_output

 - ansible.builtin.set_fact:
    do_rpm: "{{ls_output.stdout}}"

 - name: Install DO
   f5networks.f5_modules.bigip_lx_package:
    package: "~/{{do_rpm}}"
    provider: "{{provider}}"
   register: install_do

 - name: Pause for Install to complete
   ansible.builtin.pause:
     minutes: 1
   when: install_do.changed